routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route group: a groupon belüli összes routra igaz lesz.
//Groupon belül minden Controllert a Controllers/Admin-namespace alatt fog keresni.


//302 SEO FRIENDLY REDIRECT
Route::get('/regi/url', function () {
  return redirect('/uj/url');
});

Route::get('/', function () {
  return redirect()->route('customers.index');
})->name('index');

Route::middleware('customer_auth')->group(function () {
  Route::get('/ugyfelek', 'CustomersController@index')->name('customers.index');
  Route::delete('/kilepes', 'CustomerAuthController@destroy')->name('login.destroy');

  Route::get('jegyzeteim', 'NotesController@ownNotes')->name('notes.ownNotes');

  Route::delete('jegyzeteim/torles/{noteId}', 'NotesController@destroy')->name('notes.destroy');

  Route::get('/jegyzetek/uj-jegyzet', 'NotesController@create')->name('notes.create');
  Route::post('/jegyzetek/uj-jegyzet', 'NotesController@store')->name('notes.store');

  Route::get('/jegyzetek/{noteId}/modositas', 'NotesController@edit')->name('notes.edit');
  Route::put('/jegyzetek/{noteId}/modositas', 'NotesController@update')->name('notes.update');

  //a jegyzetek/ routok közül legalulra kerül, mert különben a jegyzetek/uj-jegyzet esetén az "uj-jegyzet" részt {customerId}nak gondolva ebbe futna bele.

  Route::post('/uj-hozzaszolas/{type}/{id}', 'CommentsController@store')->name('comments.store');

  Route::get('/statisztikak', 'StatsController@index')->name('stats.index');
});

Route::get('/jegyzetek/{customerId?}', 'NotesController@index')->name('notes.index');
Route::get('/jegyzet/{noteId}', 'NotesController@show')->name('notes.show');


//create, store
Route::get('/regisztracio', 'CustomersController@create')->name('customers.create');
Route::post('/regisztracio', 'CustomersController@store')->name('customers.store');


//edit, update
Route::get('/ugyfel/{customerId}/modositas', 'CustomersController@edit')->name('customers.edit');
Route::put('/ugyfel/{customerId}/modositas', 'CustomersController@update')->name('customers.update');

Route::delete('ugyfel/{customerId}/torles', 'CustomersController@destroy')->name('customers.destroy');

Route::get('/ugyfel/{id}', 'CustomersController@show')->name('customers.show');


Route::get('/belepes', 'CustomerAuthController@create')->name('login.create');

Route::post('/belepes', 'CustomerAuthController@store')->name('login.store');


//  Route::post('/login', 'Auth\LoginController@login')->name('login.store');
//Route::post('/belepes', 'CustomerAuthController@store')->name('login.store');

Route::get('/customer', 'CustomersController@newCustomer')->name('customers.newCustomer');

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () { //

  Route::namespace('Auth')->group(function () {
    Route::get('/belepes', 'LoginController@showLoginForm')->name('login.create');
    Route::post('/belepes', 'LoginController@login')->name('login.store');

    Route::get('/kilepes', 'LoginController@logout')->name('login.logout');
  });

  Route::middleware('admin_auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::post('/customers/send-mail-to-all', 'CustomersController@sendTestMailToAll')->name('customers.sendTestMailToAll');

    Route::post('/customers/send-mail/{customer}', 'CustomersController@sendTestMail')->name('customers.sendTestMail');
    Route::resource('/customers', 'CustomersController', ['except' => 'show']);
    Route::resource('/notes', 'NotesController', ['except' => 'show']);


    //Route::get('/admin/customers', 'CustomersController@index')->name('admin.customers.index');
  });
});
Route::group(['middleware' => ['cors', 'json.response']], function () {

  Route::post('api/login', 'Api\ApiController@login')->name('api.login');



  Route::middleware('auth:api')->group(function () {
    Route::get('api/getdata', 'Api\ApiController@getData')->name('api.getData');
  });

});


Route::get('social/{provider}', 'SocialAuthController@redirectToProvider')->name('social.login');
Route::get('social/{provider}/callback', 'SocialAuthController@handleProviderCallback');

Route::group(['prefix' => 'laravel-filemanager'], function () {
  \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Carbon\Carbon;
use App\Models\ModelHistoryTrait;
use Laravel\Passport\HasApiTokens;

class Customer extends Authenticatable
{

  use ModelHistoryTrait, HasApiTokens;

  //public $table = 'customers';
  protected $casts = [
    'social' => 'array'
  ];

  public function lastUpdated()
  {
    return $this->updated_at->format('Y-m-d');
  }

  public function notes()
  {
    //1 a többhöz kapcsolat
    return $this->hasMany(Note::class);
  }

  public function comments()
  {
    return $this->morphMany(Comment::class, 'commentable');
  }

  public function attachment()
  {
    return $this->morphOne(Attachment::class, 'attachable');
  }

  public function writtenComments()
  {
    return $this->hasMany(Comment::Class);
  }

  public function setAttributes($data)
  {
    $this->name = $data['name'];
    $this->email = $data['email'];

    if (isset($data['password']) && $data['password']) {
      $this->password = \Hash::make($data['password']);
    }
  }

  public function scopeSearch($query, $data)
  {
    if (isset($data['name']) && $data['name']) {   //$search['name']  = Horvath;
      $query->where('name', 'LIKE', '%' . $data['name'] . '%');
    }

    if (isset($data['email']) && $data['email']) {   //$search['name']  = Horvath;
      $query->where('email', 'LIKE', '%' . $data['email'] . '%');
    }

    if (isset($data['orderby']) && $data['orderby']) {
      $query->orderBy($data['orderby'], $data['order_dir']);
    }
  }

  public function scopeFreshRegister($query)
  {
    //a héten regisztráltak
    $date = Carbon::now()->subWeek()->format('Y-m-d');
    $query->where('created_at', '>', $date);
  }
}

app/Http/Controllers/Admin/CustomersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\Attachment;
use App\Mail\TestMail;
use App\Jobs\MailSender;

class CustomersController extends Controller
{

  public function index(Request $request)
  {
    $customer = Customer::find(1);

    $search = $request->input('search'); //array
    $search['orderby'] = $request->input('orderby');
    $search['order_dir'] = $request->input('order_dir');
    $customers = Customer::search($search)->get();

    return view('admin.customers.index')
      ->with('customers', $customers);
  }

  public function create()
  {
    $customer = new Customer;

    return view('admin.customers.create')
      ->with('customer', $customer);
  }

  public function store(Request $request)
  {
    $this->validate($request, [

      'name' => 'sajt',
      'email' => 'required|email|unique:customers,email',
      'password' => 'required|confirmed'
    ]);

    $customer = new Customer;
    $customer->setAttributes($request->all());

    try {
      $customer->save();
      session()->flash('success', 'Ügyfél létrehozva');
    } catch (\Exception $e) {
      session()->flash('error', $e->getMessage());
    }
    /* if( $customer->save()) {
       session()->flash('success', 'Ügyfél létrehozva');
     } else {
       session()->flash('error', 'Sajnos a mentés sikertelen');
     }*/


    return redirect()->route('admin.customers.index');
  }

  public function edit($customerId)
  {

    $customer = Customer::findOrFail($customerId);

    return view('admin.customers.edit')->with('customer', $customer);
  }

  public function update(Request $request, $customerId)
  {
    \Validator::extend('sajt', function($attribute, $value, $parameters) {
      return $value == 'sajt';
    });

    $this->validate($request, [
      'name' => 'sajt',
      'name' => 'required',
      'email' => 'required|email|unique:customers,email,' . $customerId,  //unique kivéve a megadott IDra
      'password' => 'confirmed',   //nem kötelező, de ha meg van adva, a 2jelszónak egyeznie kell
      'attachment' => 'file|max:4000|mimes:png,jpg'
    ]);

    $customer = Customer::findOrFail($customerId);
    $customer->setAttributes($request->all());
    $customer->save();
    if ($file = $request->file('attachment')) {
      $attachment = new Attachment;
      $attachment->addFile($file);
      $attachment->attachable()->associate($customer);
      $attachment->save();
    }


    session()->flash('success', 'Ügyfél módosítva');

    return redirect()->route('admin.customers.index');
  }

  public function destroy($customerId)
  {
    $customer = Customer::findOrFail($customerId);
    $customer->delete();

    return response()->json(['message' => 'Az ügyfél törölve']);
  }


  public function sendTestMail($customerId)
  {
    $customer = Customer::findOrFail($customerId);
    $mail = new TestMail($customer);

    /* \Mail::send('mails.test-mail', ['customer' => $customer], function ($message) use ($customer) {
       $message->to($customer->email)
               ->from('')
               ->subject('Test Email');
     });*/
    try {
      \Mail::to($customer->email)
        ->send($mail);

      \Log::info('Teszt levél kiküldve a következő címre: ' . $customer->email);
    } catch (\Exception $e) {
      \Log::error($e->getMessage());
    }
    session()->flash('success', 'Teszt levél kiküldve a következő címre: ' . $customer->email);

    return redirect()->back();
  }


  public function sendTestMailToAll(Request $request)
  {
    $customers = Customer::all();

    dispatch(new MailSender($customers));

    session()->flash('success', 'Teszt levelek kiküldve');
    return redirect()->back();

  }
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Customer;

class CustomersController extends Controller
{
  public function show($customerId)
  {
    $customer = Customer::find($customerId);

    return view('frontend.customers.show')->with('customer', $customer);
  }

  public function index(Request $request)
  {
    $search = $request->input('search'); //array
    $search['orderby'] = $request->input('orderby');
    $search['order_dir'] = $request->input('order_dir');

    $customers = Customer::search($search)->get();

    return view('frontend.customers.index')
            ->with('customers', $customers);
  }


}

resources/views/admin/customers/create.blade.php
@extends('admin.layout.admin-layout')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Ügyfél létrehozása</h3>
        </div>
        @include('admin.customers.form')
      </div>
    </div>
  </div>
@stop

resources/views/admin/customers/edit.blade.php
@extends('admin.layout.admin-layout')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Ügyfél módosítása - {{$customer->name}}</h3>
        </div>
        @include('admin.customers.form')
      </div>
    </div>
  </div>
@stop

resources/views/admin/customers/form.blade.php
<form role="form"
      action="{{$customer->id ? route('admin.customers.update', $customer->id) : route('admin.customers.store')}}"
      enctype="multipart/form-data"
      method="POST">
  @if($customer->id)
    <input type="hidden" name="_method" value="PUT">{{--PATCH--}}
  @endif
  @csrf
  <div class="box-body">
    <div class="form-group {{$errors->first('name') ? 'has-error' : ''}}">
      <label>Név</label>
      <input type="text" class="form-control"  placeholder="Név" name="name"
             value="{{old('name', $customer->name)}}">
      @if($errors->first('name'))
        <span class="help-block">{{$errors->first('name')}}</span>
      @endif
    </div>
    <div class="form-group {{$errors->first('email') ? 'has-error' : ''}}">
      <label for="exampleInputEmail1">Email</label>
      <input type="text" class="form-control" id="exampleInputEmail1" name="email" placeholder="Enter email"
             value="{{old('email', $customer->email)}}">
      @if($errors->first('email'))
        <span class="help-block">{{$errors->first('email')}}</span>
      @endif
    </div>
    <div class="form-group {{$errors->first('password') ? 'has-error' : ''}}">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
      @if($errors->first('password'))
        <span class="help-block">{{$errors->first('password')}}</span>
      @endif
    </div>
    <div class="form-group {{$errors->first('password_confirmation') ? 'has-error' : ''}}">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="password_confirmation" placeholder="Password">
      @if($errors->first('password_confirmation'))
        <span class="help-block">{{$errors->first('password_confirmation')}}</span>
      @endif
    </div>
    <div class="form-group {{$errors->first('attachment') ? 'has-error' : ''}}">
      <label for="exampleInputFile">Profilkép</label>
      <input type="file" name="attachment" id="exampleInputFile">
      @if($errors->first('attachment'))
        <p class="help-block has-error text-danger red">{{$errors->first('attachment')}}</p>
      @endif
    </div>
    {{-- <div class="checkbox">
       <label>
         <input type="chveckbox"> Check me out
       </label>
     </div>--}}
  </div>
  <!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-success">Mentés</button>
  </div>
</form>

resources/views/admin/customers/index.blade.php
@extends('admin.layout.admin-layout')

@section('content')
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Ügyfelek</h3>
          <div class="card-tools">
            <a href="{{route('admin.customers.create')}}" class="btn btn-primary">Ügyfél létrehozás</a>

            <form action="{{route('admin.customers.sendTestMailToAll')}}" method="POST">
              @csrf
              <button type="submit" class="btn btn-sm btn-warning">Értesítési mail küldése</button>
            </form>
          </div>
        </div>
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
            <tr>
              <th>{!! orderTableHeader('id', 'Id') !!}</th>
              <th>{!! orderTableHeader('name', 'Név') !!}</th>
              <th>{!! orderTableHeader('email', 'Email') !!}</th>
              <th>Jegyzetek</th>
              <th></th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach($customers as $customer)
              <tr>
                <td>{{$customer->id}}</td>
                <td>{{$customer->name}}</td>
                <td>{{$customer->email}}</td>
                <td>
                  <a href="{{route('admin.notes.index', ['search' => ['customer' => ['name' => $customer->name]]])}}"
                     role="button" target="_blank" class="btn btn-sm btn-secondary">
                    Jegyzetek ({{$customer->notes()->count()}})
                  </a>
                </td>
                <td>
                  <form action="{{route('admin.customers.sendTestMail', $customer->id)}}" method="POST">
                    @csrf
                    <button type="submit" class="btn btn-sm btn-warning">Levél küldése</button>
                  </form>
                </td>

                <td>
                  <a href="{{route('admin.customers.edit', $customer->id)}}" class="btn btn-default btn-sm">Módosítás <i
                      class="fa fa-sw fa-sm fa-edit"></i></a>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
@stop