routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route group: a groupon belüli összes routra igaz lesz.
//Groupon belül minden Controllert a Controllers/Admin-namespace alatt fog keresni.


//302 SEO FRIENDLY REDIRECT
Route::get('/regi/url', function () {
  return redirect('/uj/url');
});

Route::get('/', function () {
  return redirect()->route('customers.index');
})->name('index');

Route::middleware('customer_auth')->group(function () {
  Route::get('/ugyfelek', 'CustomersController@index')->name('customers.index');
  Route::delete('/kilepes', 'CustomerAuthController@destroy')->name('login.destroy');

  Route::get('jegyzeteim', 'NotesController@ownNotes')->name('notes.ownNotes');

  Route::delete('jegyzeteim/torles/{noteId}', 'NotesController@destroy')->name('notes.destroy');

  Route::get('/jegyzetek/uj-jegyzet', 'NotesController@create')->name('notes.create');
  Route::post('/jegyzetek/uj-jegyzet', 'NotesController@store')->name('notes.store');

  Route::get('/jegyzetek/{noteId}/modositas', 'NotesController@edit')->name('notes.edit');
  Route::put('/jegyzetek/{noteId}/modositas', 'NotesController@update')->name('notes.update');

  //a jegyzetek/ routok közül legalulra kerül, mert különben a jegyzetek/uj-jegyzet esetén az "uj-jegyzet" részt {customerId}nak gondolva ebbe futna bele.

  Route::post('/uj-hozzaszolas/{type}/{id}', 'CommentsController@store')->name('comments.store');

  Route::get('/statisztikak', 'StatsController@index')->name('stats.index');
});

Route::get('/jegyzetek/{customerId?}', 'NotesController@index')->name('notes.index');
Route::get('/jegyzet/{noteId}', 'NotesController@show')->name('notes.show');


//create, store
Route::get('/regisztracio', 'CustomersController@create')->name('customers.create');
Route::post('/regisztracio', 'CustomersController@store')->name('customers.store');


//edit, update
Route::get('/ugyfel/{customerId}/modositas', 'CustomersController@edit')->name('customers.edit');
Route::put('/ugyfel/{customerId}/modositas', 'CustomersController@update')->name('customers.update');

Route::delete('ugyfel/{customerId}/torles', 'CustomersController@destroy')->name('customers.destroy');

Route::get('/ugyfel/{id}', 'CustomersController@show')->name('customers.show');


Route::get('/belepes', 'CustomerAuthController@create')->name('login.create');

Route::post('/belepes', 'CustomerAuthController@store')->name('login.store');


//  Route::post('/login', 'Auth\LoginController@login')->name('login.store');
//Route::post('/belepes', 'CustomerAuthController@store')->name('login.store');

Route::get('/customer', 'CustomersController@newCustomer')->name('customers.newCustomer');

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () { //

  Route::namespace('Auth')->group(function () {
    Route::get('/belepes', 'LoginController@showLoginForm')->name('login.create');
    Route::post('/belepes', 'LoginController@login')->name('login.store');

    Route::get('/kilepes', 'LoginController@logout')->name('login.logout');
  });

  Route::middleware('admin_auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::post('/customers/send-mail-to-all', 'CustomersController@sendTestMailToAll')->name('customers.sendTestMailToAll');

    Route::post('/customers/send-mail/{customer}', 'CustomersController@sendTestMail')->name('customers.sendTestMail');
    Route::resource('/customers', 'CustomersController', ['except' => 'show']);
    Route::resource('/notes', 'NotesController', ['except' => 'show']);


    //Route::get('/admin/customers', 'CustomersController@index')->name('admin.customers.index');
  });
});
Route::group(['middleware' => ['cors', 'json.response']], function () {

  Route::post('api/login', 'Api\ApiController@login')->name('api.login');



  Route::middleware('auth:api')->group(function () {
    Route::get('api/getdata', 'Api\ApiController@getData')->name('api.getData');
  });

});


Route::get('social/{provider}', 'SocialAuthController@redirectToProvider')->name('social.login');
Route::get('social/{provider}/callback', 'SocialAuthController@handleProviderCallback');

Route::group(['prefix' => 'laravel-filemanager'], function () {
  \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/admin/layout/admin-layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Admin oldal</title>

  <link href="{{asset('css/admin.css')}}" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    @include('admin.layout.upper_nav_bar')
    @include('admin.layout.left_menu_bar')
    <div class="content-wrapper">
      <div class="content">
        @include('admin.layout.message')
        @include('sse::view')
        <div class="container-fluid">
          @yield('content')
        </div>
      </div>
    </div>
  </div>
  <script src="{{asset('js/admin.js')}}"></script>
  @yield('extra-scripts')
</body>
</html>

resources/views/admin/layout/left_menu_bar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{{route('admin.dashboard')}}" class="brand-link">
    <span class="brand-text font-weight-light">Admin</span>
  </a>
  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <a href="{{route('admin.dashboard')}}" class="nav-link {{\Route::currentRouteName() == 'admin.dashboard' ? ' active' : ''}}">
            <i class="nav-icon fas fa-th"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>
        <li class="nav-item has-treeview {{activeAdminMenu(['customers', 'notes']) ? 'menu-open' : ''}}">
          <a href="#" class="nav-link {{activeAdminMenu(['customers', 'notes']) ? 'active' : ''}}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Tartalom
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{route('admin.customers.index')}}" class="nav-link {{activeAdminMenu('customers') ? 'active' : ''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>Ügyfelek</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{route('admin.notes.index')}}" class="nav-link {{activeAdminMenu('notes') ? 'active' : ''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>Jegyzetek</p>
              </a>
            </li>
          </ul>
        </li>

      {{--  <li class="nav-item">
          <a href="{{route('admin.customers.index')}}" class="nav-link{{\Route::currentRouteName() == 'admin.customers.index' ? ' active' : ''}}">
            <i class="nav-icon fas fa-th"></i>
            <p>
              Ügyfelek
            </p>
          </a>
        </li>--}}
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

resources/views/admin/layout/message.blade.php
@if(session()->has('success'))
  <div class="alert alert-success ">
  <i class="icon fa fa-check"></i>
    {{session('success')}}
  </div>
@endif
@if(session()->has('error'))
  <div class="alert alert-danger alert-dismissible">

   <i class="icon fa fa-ban"></i>
    {{session('error')}}
  </div>
@endif

resources/views/admin/layout/upper_nav_bar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">

    <li class="nav-item dropdown user-menu">
      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class="d-none d-md-inline">{{$admin->name}} <i class="fas fa-fw fa-cog"></i></span>
      </a>
      <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
        <li class="user-header bg-primary" style="height:auto;">
          <p>
            {{$admin->email}}
          </p>
        </li>

        <li class="user-footer">
          <a href="{{route('admin.login.logout')}}" class="btn btn-secondary btn-sm btn-flat float-right">Kilépés <i
              class="fas fa-fw fa-sm fa-sign-out-alt"></i></a>
        </li>
      </ul>
    </li>
  </ul>

</nav>