routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route group: a groupon belüli összes routra igaz lesz.
//Groupon belül minden Controllert a Controllers/Admin-namespace alatt fog keresni.


//302 SEO FRIENDLY REDIRECT
Route::get('/regi/url', function () {
  return redirect('/uj/url');
});

Route::get('/', function () {
  return redirect()->route('customers.index');
})->name('index');

Route::middleware('customer_auth')->group(function () {
  Route::get('/ugyfelek', 'CustomersController@index')->name('customers.index');
  Route::delete('/kilepes', 'CustomerAuthController@destroy')->name('login.destroy');

  Route::get('jegyzeteim', 'NotesController@ownNotes')->name('notes.ownNotes');

  Route::delete('jegyzeteim/torles/{noteId}', 'NotesController@destroy')->name('notes.destroy');

  Route::get('/jegyzetek/uj-jegyzet', 'NotesController@create')->name('notes.create');
  Route::post('/jegyzetek/uj-jegyzet', 'NotesController@store')->name('notes.store');

  Route::get('/jegyzetek/{noteId}/modositas', 'NotesController@edit')->name('notes.edit');
  Route::put('/jegyzetek/{noteId}/modositas', 'NotesController@update')->name('notes.update');

  //a jegyzetek/ routok közül legalulra kerül, mert különben a jegyzetek/uj-jegyzet esetén az "uj-jegyzet" részt {customerId}nak gondolva ebbe futna bele.

  Route::post('/uj-hozzaszolas/{type}/{id}', 'CommentsController@store')->name('comments.store');

  Route::get('/statisztikak', 'StatsController@index')->name('stats.index');
});

Route::get('/jegyzetek/{customerId?}', 'NotesController@index')->name('notes.index');
Route::get('/jegyzet/{noteId}', 'NotesController@show')->name('notes.show');


//create, store
Route::get('/regisztracio', 'CustomersController@create')->name('customers.create');
Route::post('/regisztracio', 'CustomersController@store')->name('customers.store');


//edit, update
Route::get('/ugyfel/{customerId}/modositas', 'CustomersController@edit')->name('customers.edit');
Route::put('/ugyfel/{customerId}/modositas', 'CustomersController@update')->name('customers.update');

Route::delete('ugyfel/{customerId}/torles', 'CustomersController@destroy')->name('customers.destroy');

Route::get('/ugyfel/{id}', 'CustomersController@show')->name('customers.show');


Route::get('/belepes', 'CustomerAuthController@create')->name('login.create');

Route::post('/belepes', 'CustomerAuthController@store')->name('login.store');


//  Route::post('/login', 'Auth\LoginController@login')->name('login.store');
//Route::post('/belepes', 'CustomerAuthController@store')->name('login.store');

Route::get('/customer', 'CustomersController@newCustomer')->name('customers.newCustomer');

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () { //

  Route::namespace('Auth')->group(function () {
    Route::get('/belepes', 'LoginController@showLoginForm')->name('login.create');
    Route::post('/belepes', 'LoginController@login')->name('login.store');

    Route::get('/kilepes', 'LoginController@logout')->name('login.logout');
  });

  Route::middleware('admin_auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::post('/customers/send-mail-to-all', 'CustomersController@sendTestMailToAll')->name('customers.sendTestMailToAll');

    Route::post('/customers/send-mail/{customer}', 'CustomersController@sendTestMail')->name('customers.sendTestMail');
    Route::resource('/customers', 'CustomersController', ['except' => 'show']);
    Route::resource('/notes', 'NotesController', ['except' => 'show']);


    //Route::get('/admin/customers', 'CustomersController@index')->name('admin.customers.index');
  });
});
Route::group(['middleware' => ['cors', 'json.response']], function () {

  Route::post('api/login', 'Api\ApiController@login')->name('api.login');



  Route::middleware('auth:api')->group(function () {
    Route::get('api/getdata', 'Api\ApiController@getData')->name('api.getData');
  });

});


Route::get('social/{provider}', 'SocialAuthController@redirectToProvider')->name('social.login');
Route::get('social/{provider}/callback', 'SocialAuthController@handleProviderCallback');

Route::group(['prefix' => 'laravel-filemanager'], function () {
  \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;


class Note extends SearchModel
{
  use ModelHistoryTrait;

  public function hasTag($tagId)
  {
    return $this->tags()->find($tagId);
  }

  public function customer()
  { //1-többhöz kapcsolat, 'customer_id'  idegen kulcsal.
    //  return $this->belongsTo(Customer::class/*, 'customer_id'*/);/*Default elnevezésnél nem kell megadni*/
    return $this->belongsTo(Customer::class);
  }

  public function tags()
  {
    return $this->belongsToMany(Tag::class)->withTimestamps();
  }

  public function comments()
  {
    return $this->morphMany(Comment::class, 'commentable');
  }

  public function setAttributes($data)
  {
    $this->content = isset($data['content']) ? $data['content'] : '';
    $this->public_at =  isset($data['public_at']) ? $data['public_at'] : null;
    $this->title =  isset($data['title']) ? $data['title'] : null;
  }

  public function scopeOnFrontend($query)
  {
    $query->whereNotNull('public_at')->whereDate('public_at', '<=', now());
  }

}

app/Http/Controllers/Admin/NotesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Note;
use App\Models\Customer;
use App\Models\Attachment;

class NotesController extends Controller
{

  public function index(Request $request)
  {
    $search = $request->input('search'); //array
    $search['sort_by'] = $request->input('orderby');
    $search['sorting_direction'] = $request->input('order_dir');
  //  $notes = Note::search($search)->get();
    $customers = Customer::orderBy('name')->get();

    $notes = Note::search($search)->orderBy('created_at', 'desc')->paginate(5);

    return view('admin.notes.index')
      ->with('notes', $notes)
      ->with('customers', $customers);
  }

  public function create()
  {
    $note = new Note;
    $customers = Customer::orderBy('name')->get();

    return view('admin.notes.create')
        ->with('note', $note)
      ->with('customers', $customers);
  }

  public function store(Request $request)
  {
    $this->validate($request, [   //a customer táblja Idjai közül
      'customer_id' => 'required|exists:customers,id'
    ]);
    $note = new Note;
    $note->setAttributes($request->all());
    $note->customer_id = $request->input('customer_id');
    try {
      $note->save();
      session()->flash('success', 'Kiadvány létrehozva');
    } catch(\Exception $e) {
      session()->flash('error', $e->getMessage());
    }

    return redirect()->route('admin.notes.index', ['page' => $request->input('page')]);
  }

  public function edit($noteId)
  {
    $note = Note::findOrFail($noteId);
    $customers = Customer::orderBy('name')->get();

    return view('admin.notes.edit')
      ->with('note', $note)
      ->with('customers', $customers);
  }

  public function update(Request $request, $noteId)
  {
    $this->validate($request, [
      'customer_id' => 'required|exists:customers,id'
    ]);

    $note = Note::findOrFail($noteId);
    $note->setAttributes($request->all());
    $note->customer_id = $request->input('customer_id');
    $note->save();
    if($file = $request->file('attachment')) {
      $attachment = new Attachment;
      $attachment->addFile($file);
      $attachment->attachable()->associate($note);
      $attachment->save();
    }

    session()->flash('success', 'Kiadvány módosítva');

    return redirect()->route('admin.notes.index', ['page' => $request->input('page')]);
  }

  public function destroy($noteId)
  {
    $note = Note::findOrFail($noteId);
    $note->delete();

    return response()->json(['message' => 'Az ügyfél törölve']);
  }

}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Note;
use App\Models\Customer;
use Carbon\Carbon;
use App\Models\Tag;

class NotesController extends Controller
{

  public function __construct()
  {
    $this->middleware('own_note')->only(['edit', 'update', 'destroy']);
  }

  public function show($noteId)
  {
    $note = Note::findOrFail($noteId);

    return view('frontend.notes.show')->with('note', $note);
  }

                        //ha nincs megadva, akkor null
  public function index($customerId = null)
  {
    if($customerId) {
        $customer = Customer::find($customerId);
        $notes = $customer->notes; //$customer->notes()->get(); rövid formája

        $now = Carbon::now();
        //csak mai jegyzetek.       //whereDate: elég ha a dátum egyezik, az időpont részt figyelmen kívül hagyja.
        $notes = $customer->notes()->whereDate('created_at', '=', $now)->orderBy('created_at', 'desc')->get();
    }

    $notes = Note::onFrontend()->get();

    return view('frontend.notes.index')->with('notes', $notes);
  }

  public function create()
  {                 //ha nincs megadva másik paraméter az orderBy() nál akkor növekvőbe rendez.
    $tags = Tag::orderBy('name')->get();

    return view('frontend.notes.create')->with('tags', $tags);
  }


  public function store(Request $request)
  {
      $note = new Note;
      $note->customer_id = auth()->guard('customer')->id();// ugyanaz, mint  $note->customer()->associate(auth()->guard('customer')->id())
      $note->setAttributes($request->all());
      $note->save();
      //fontos, hogy a save az attach előtt szerepeljen, mert csak a save() után, az adatbázisba kerüléskor kap a $note id-t.
      $note->tags()->attach($request->input('tags'));

      return redirect()->route('notes.ownNotes');
  }

  public function edit($noteId)
  {
    $note = authCustomer()->notes()->findOrFail($noteId);
    $tags = Tag::orderBy('name')->get();

    return view('frontend.notes.edit')
    ->with('note', $note)
    ->with('tags', $tags);
  }

  public function update(Request $request, $noteId)
  {
      $note = Note::find($noteId);
      $note->setAttributes($request->all());
      $note->save();

      $note->tags()->sync($request->input('tags'));

      return redirect()->route('notes.ownNotes');
  }

  public function ownNotes()
  {
    $notes = authCustomer()->notes;

    return view('frontend.notes.own-notes')
      ->with('notes', $notes);
  }

  public function destroy($customerId)
  {
      $customer = Customer::findOrFail($customerId);
      $customer->delete();

      return response()->json(['message' => 'A jegyzet törölve']);
  }

}

resources/views/admin/notes/create.blade.php
@extends('admin.layout.admin-layout')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Kiadvány létrehozása</h3>
        </div>
        @include('admin.notes.form')
      </div>
    </div>
  </div>
@stop

@section('extra-scripts')
  <script src="{{asset('vendor/japonline/laravel-ckeditor/ckeditor.js')}}"></script>

{{--
ez a default működés
<script>
    CKEDITOR.replace('.ckeditor');
  </script>--}}
@endsection

resources/views/admin/notes/edit.blade.php
@extends('admin.layout.admin-layout')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Kiadvány módosítása - {{$note->name}}</h3>
        </div>
        @include('admin.notes.form')
      </div>
    </div>
  </div>
@stop

@section('extra-scripts')
  <script src="{{asset('vendor/japonline/laravel-ckeditor/ckeditor.js')}}"></script>
  {{--
  ez a default működés
  <script>
      CKEDITOR.replace('.ckeditor');
    </script>--}}
@endsection

resources/views/admin/notes/form.blade.php
<form role="form"
      action="{{$note->id ?
        route('admin.notes.update', ['note' => $note->id, 'page' => request()->input('page')]) :
        route('admin.notes.store', ['page' => request()->input('page')])}}"
      enctype="multipart/form-data"
      method="POST">
  @if($note->id)
    <input type="hidden" name="_method" value="PUT">{{--PATCH--}}
  @endif
  @csrf
  <div class="box-body">
    <div class="form-group {{$errors->first('customer_id') ? 'has-error' : ''}}">
     <label>Ügyfél</label>
      <select name="customer_id" class="form-control form-control-sm tags">
        @foreach($customers as $customer)
          <option value="{{$customer->id}}" {{old('customer_id') == $customer->id ? 'selected' : ''}}>
            {{$customer->name}} ({{$customer->email}})
          </option>
        @endforeach
      </select>
      @if($errors->first('customer_id'))
        <p class="help-block has-error text-danger red">{{$errors->first('customer_id')}}</p>
      @endif
    </div>
    <div class="form-group {{$errors->first('name') ? 'has-error' : ''}}">
      <label>Cím</label>
      <input type="text" class="form-control" placeholder="Cím" name="title"
             value="{{old('title', $note->name)}}">
      @if($errors->first('title'))
        <span class="help-block">{{$errors->first('title')}}</span>
      @endif
    </div>
    <div class="form-group {{$errors->first('content') ? 'has-error' : ''}}">
      <label for="exampleInputEmail1">Jegyzet</label>
      <textarea class="form-control ckeditor" name="content"
      >{{old('content', $note->content)}}</textarea>
      @if($errors->first('content'))
        <span class="help-block">{{$errors->first('content')}}</span>
      @endif
    </div>
    <div class="form-group {{$errors->first('attachment') ? 'has-error' : ''}}">
     <label>Kép</label>
      <input type="file" name="attachment" id="exampleInputFile">
      @if($errors->first('attachment'))
        <p class="help-block has-error text-danger red">{{$errors->first('attachment')}}</p>
      @endif
    </div>
  </div>
  <!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-success">Mentés</button>
  </div>
</form>

resources/views/admin/notes/index.blade.php
@extends('admin.layout.admin-layout')

@section('content')
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Kiadványok</h3>
          <div class="card-tools">
            <a href="{{route('admin.notes.create')}}" class="btn btn-success btn-sm">Kiadvány létrehozás <i class="fa fa-fw fa-sm fa-plus"></i></a>
          </div>
        </div>
        <div class="card-body table-responsive p-0">
          <form action="{{route('admin.notes.index')}}" method="GET">
            <table class="table table-hover table-striped text-nowrap">
              <thead>
              <tr>
                <th>{!! orderTableHeader('id', 'Id') !!}</th>
                <th>{!! orderTableHeader('customer.name', 'Ügyfél') !!}</th>
                <th>{!! orderTableHeader('title', 'Cím') !!}</th>
                <th>{!! orderTableHeader('created_at', 'Dátum') !!}</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td><input type="text" class="form-control form-control-sm" name="search[id]"
                           value="{{request()->input('search.id')}}"></td>
                <td><input type="text" class="form-control form-control-sm" name="search[customer][name]"
                           value="{{request()->input('search.customer.name')}}"></td>
                <td><input type="text" class="form-control form-control-sm" name="search[title]"
                           value="{{request()->input('search.title')}}"></td>
                <td><input type="text" class="form-control form-control-sm" name="search[created_at]"
                           value="{{request()->input('search.created_at')}}"></td>
                <td>
                  <div class="btn-group">
                    <input role="button" type="submit" class="btn btn-primary btn-sm" value="Keresés">
                    <a role="button" class="btn btn-default btn-sm" href="{{route('admin.notes.index')}}"
                       title="Keresési feltételek törlése"><i class="fa fa-sync"></i></a>
                  </div>

                </td>
              </tr>
              @foreach($notes as $note)
                <tr>
                  <td>{{$note->id}}</td>
                  <td>{{$note->customer ? $note->customer->name : ''}}</td>
                  <td>{{$note->title}}</td>
                  <td>{{$note->created_at->format('Y-m-d')}}</td>
                  <td>
                    <div class="btn-group">
                    <a href="{{route('admin.notes.edit', ['note' => $note->id, 'page' => request()->input('page')])}}"
                       class="btn btn-default btn-sm">
                       <i class="far fa-sw fa-sm fa-edit"></i> Módosítás
                     </a>
                      <button data-url="{{route('admin.notes.destroy', $note->id)}}"
                              data-token="{{csrf_token()}}"
                              type="button" role="button"
                              class="btn btn-danger btn-sm confirm-delete">
                        Törlés <i class="far fa-fw fa-sm fa-trash-alt"></i>
                      </button>
                    </div>
                  </td>
                </tr>
              @endforeach
              </tbody>
            </table>
          </form>
          <div class="d-flex justify-content-center">
            {{ $notes->links('vendor.pagination.bootstrap-4') }}
          </div>

        </div>
      </div>
    </div>
  </div>
@stop